### ISSUE TITLE
no bin/www directory, null error after run by 'node app.js'

### ISSUE THREAD

**Issue by offeragregator** [Azure-Samples/media-services-node-vod#1]
Hi I wanted to try this, but I figured out 2 errors:
1. after npm install & bower install there is missing bin/www as is written in wiki
2. after 'node app.js '  there is only 'null' written in terminal. 
I figured out that it comes from async.waterfall , from  error method  function (err) {
    console.log(err);
  }.

Does anybody know what coud be a problem ?

**Comment by VaanPan** [comment]
sorry for the mistake, bin folder was by default ignored.
I have added this folder into repo.
